### ISSUE TITLE
Uncertain Language Support

### ISSUE THREAD

**Issue by Circuitbreaker08** [Uncover-F/TAS#1]
The repo currently has no indication of what languages are supported by the API, forcing users to play a guessing game.

**Comment by Circuitbreaker08** [comment]
I am currently working on a fork to address this issue.

**Comment by Circuitbreaker08** [comment]
Issued [this PR](https://github.com/Uncover-F/TAS/pull/2) to correct this lack of information.

**Comment by Uncover-F** [comment]
Sure I'll find out and post a list! If you would like to join in the development of the project, just contact me :) Thank you for assisting in the development of the TAS api. I've merged your fork into the main repo.
