### ISSUE TITLE
Hey, How many Languages it can support?

### ISSUE THREAD

**Issue by SamirXR** [Uncover-F/TAS#3]
> Hey, How many Languages it can support?

I would be very Greateful to know, i'm using this on My Discord Bot Project.

Repository : https://github.com/SamirXR/Nyx-Bot

**Comment by Uncover-F** [comment]
A lot, actually.
I do not know the exact language codes but it is on the lines like:
en, fr, zh, 
and so on.

But I need to say, only standard languages will work.
For Example: en will work but en-us may not

Get a language code, try it, and, it should work.
Sorry if this was not helpful.

**Comment by Uncover-F** [comment]
Again, sorry, but it is really limited to the languages you want.

**Comment by SamirXR** [comment]
Hey Thanks for response! i got it to work for these languages hopefully it can be Helpful for you!

| Code | Language     |
|------|--------------|
| en   | English      |
| es   | Spanish      |
| fr   | French       |
| de   | German       |
| ja   | Japanese     |
| ru   | Russian      |
| ar   | Arabic       |
| pt   | Portuguese   |
| it   | Italian      |
| nl   | Dutch        |
| ko   | Korean       |
| tr   | Turkish      |
| sv   | Swedish      |
| hi   | Hindi        |
| pl   | Polish       |
| vi   | Vietnamese   |
| el   | Greek        |
| fi   | Finnish      |
| zh   | Chinese      |

**Comment by Uncover-F** [comment]
Thank you, and if you search up any language (2 letter only) it will come up :)

**Comment by Uncover-F** [comment]
https://www.loc.gov/standards/iso639-2/php/code_list.php
Check ISO 639-1 Code Column
