### ISSUE TITLE
Site can't be reach

### ISSUE THREAD

**Issue by jcid11** [Uncover-F/TAS#5]
I ve been using this url for a personal project im working on... but for almost the whole day every time you try to go or consume the service its just not working... if you try to go from the url you will receive a 'this site cant be reached' or if you try to consume it this is the exception you will be receiving 'ClientException with SocketException: Failed host lookup: '665.uncovernet.workers.dev''

**Comment by Uncover-F** [comment]
Hmm, we have fixed it please try again, if it does not work try from another network or computor.

**Comment by Uncover-F** [comment]
There is a new endpoint to replace '665.uncovernet.workers.dev' please check the repository. Sorry for any inconvenience.

**Comment by jcid11** [comment]
Awesome! yeah now its working perfectly... and a friendly reminder... anything that can be accessed from the url is pretty a GET endpoint... which makes it truly wonderful and easy to use for projects!! Thanks

**Comment by jcid11** [comment]
one thing to do take in count... the service is working perfectly once again... but sometimes its bringing some symbols that it didnt use to show before... For example...

{inputs: {text: greetings, source_lang: en, target_lang: de}, response: {translated_text: GrÃ¼Ãe}}

but the german translation is working fine as you can see here

TranslationStatus.loading
I/flutter ( 4183): {inputs: {text: good morning, source_lang: en, target_lang: de}, response: {translated_text: Guten Morgen}}

**Comment by jcid11** [comment]
another example:

{inputs: {text: good morning, source_lang: en, target_lang: es}, response: {translated_text: Buen dÃ­a}}

**Comment by jcid11** [comment]
even though... im not really sure why this is happening... the symbols im sometimes getting only happens on the mobile emulator(the personal project im working on is a mobile project) but when i try the same url with the same paremeters it doesnt happen..

**Comment by Uncover-F** [comment]
Thank you for using TAS. :)
